services:
  - type: web
    name: keeper-app
    env: node
    buildCommand: npm install && NODE_OPTIONS=--openssl-legacy-provider npm run build
    startCommand: npm start
    envVars:
      - key: SKIP_PREFLIGHT_CHECK
        value: "true"
      - key: NODE_OPTIONS
        value: "--openssl-legacy-provider"
